###
GET http://localhost:5000/reports/4

###
GET http://localhost:5000/reports/4?model=Boeing 757

###
GET http://localhost:5000/reports/4?month=2021-01

###
GET http://localhost:5000/reports/4?model=Boeing 737&month=2021-01

###
GET http://localhost:5000/reports/1

###
GET http://localhost:5000/reports/2

###
GET http://localhost:5000/reports/3

###
GET http://localhost:5000/reports/3?destination=BIA

###
GET http://localhost:5000/reports/3?destination=BIA&startDate=2021-03-14&endDate=2021-03-15

###
GET http://localhost:5000/reports/5