###
GET http://localhost:5000/reports/4

###
GET http://localhost:5000/reports/4?model=Boeing 757

###
GET http://localhost:5000/reports/4?month=2021-01

###
GET http://localhost:5000/reports/4?model=Boeing 737&month=2021-01

###
GET http://localhost:5000/reports/1

###
GET http://localhost:5000/reports/2

###
GET http://localhost:5000/reports/3?destination=ADS

###
GET http://localhost:5000/reports/5